
# tap repositories and their packages

tap homebrew/dupes

tap homebrew/dupes

tap homebrew/php

tap homebrew/versions

tap argon/mas
brew mas

tap caskroom/cask

tap caskroom/versions

tap eugenmayer/dockersync
brew unison
brew unox

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew Graphviz
brew ag
brew ansible
brew aom
brew autoconf
brew automake
brew cairo
brew cmake
brew curl --with-ssl --with-libah2
brew czmq
brew dav1d
brew docker-machine-nfs
brew ffmpeg
brew flac
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew fswatch
brew gcc5
brew gd
brew gdbm
brew gettext
brew giflib
brew git
brew git-ftp
brew glib
brew gmp
brew gnutls
brew gobject-introspection
brew graphite2
brew harfbuzz
brew icu4c
brew ilmbase
brew imagemagick
brew isl@0.14
brew jemalloc
brew jenkins
brew jpeg
brew lame
brew leptonica
brew lftp
brew libass
brew libbluray
brew libde265
brew libevent
brew libffi
brew libheif
brew libidn
brew libidn2
brew libmpc
brew libogg
brew libomp
brew libpgm
brew libpng
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libspiro
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvidstab
brew libvorbis
brew libvpx
brew libvterm
brew libxml2
brew libyaml
brew little-cms2
brew lua
brew luajit
brew lzo
brew makedepend
brew mpfr
brew msgpack
brew mysql
brew neovim
brew nettle
brew nim
brew node
brew norm
brew npm
brew nvm
brew opencore-amr
brew openexr
brew openjpeg
brew openssl
brew openssl@1.1
brew opus
brew p11-kit
brew pango
brew pcre
brew peco
brew php56
brew pixman
brew pkg-config
brew pulumi
brew pyenv
brew pyenv-virtualenv
brew python
brew python3
brew python@3.8
brew rav1e
brew rbenv
brew readline
brew reattach-to-user-namespace
brew rsync
brew rtmpdump
brew rubberband
brew ruby-build
brew sdl2
brew shared-mime-info
brew snappy
brew speex
brew sphinx-doc
brew sqlite
brew srt
brew tesseract
brew theora
brew tmux
brew unbound
brew unibilium
brew unixodbc
brew webp
brew x264
brew x265
brew xvid
brew xz
brew yarn --without-node
brew zeromq

# Other Cask applications
cask java
cask java7
cask macdown
cask vagrant
cask vagrant-manager

# App Store applications
appstore 682658836 GarageBand
appstore 408981434 iMovie
appstore 409183694 Keynote
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 497799835 Xcode

# Other commands
update || true
