
# tap repositories and their packages

tap argon/mas
brew mas

tap caskroom/cask
cask java
cask vagrant-manager
cask vagrant

tap caskroom/versions
cask java7

tap homebrew/dupes

tap homebrew/versions

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ag
brew ansible
brew autoconf
brew automake
brew cairo
brew cmake
brew czmq
brew fontconfig
brew fontforge
brew freetype
brew gettext
brew giflib
brew git
brew glib
brew gobject-introspection
brew graphite2
brew harfbuzz
brew icu4c
brew jpeg
brew libevent
brew libffi
brew libpgm
brew libpng
brew libsodium
brew libspiro
brew libtiff
brew libtool
brew libyaml
brew makedepend
brew mysql
brew norm
brew npm
brew nvm
brew openssl
brew pango
brew pcre
brew peco
brew pixman
brew pkg-config
brew rbenv
brew reattach-to-user-namespace
brew ruby-build
brew sphinx-doc
brew tmux
brew xz
brew zeromq

# App Store applications
appstore 682658836 GarageBand
appstore 409183694 Keynote
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 497799835 Xcode
appstore 408981434 iMovie

# Other commands
update || true
