
# tap repositories and their packages

tap argon/mas

tap caskroom/cask

tap caskroom/versions

tap homebrew/dupes

tap homebrew/dupes

tap homebrew/php

tap homebrew/versions

tap rcmdnk/file

# Other Homebrew packages
brew ag
brew ansible
brew autoconf
brew automake
brew brew-file
brew cairo
brew cmake
brew czmq
brew docker-machine-nfs
brew fontconfig
brew fontforge
brew freetype
brew gcc5
brew gettext
brew giflib
brew git
brew glib
brew gmp
brew gobject-introspection
brew graphite2
brew harfbuzz
brew icu4c
brew isl@0.14
brew jenkins
brew jpeg
brew libevent
brew libffi
brew libmpc
brew libpgm
brew libpng
brew libsodium
brew libspiro
brew libtiff
brew libtool
brew libxml2
brew libyaml
brew lua
brew luajit
brew makedepend
brew mas
brew mpfr
brew mysql
brew norm
brew npm
brew nvm
brew openssl
brew pango
brew pcre
brew peco
brew php56
brew pixman
brew pkg-config
brew python
brew python3
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew sphinx-doc
brew tmux
brew unixodbc
brew vim --with-lua
brew xz
brew zeromq

# Cask applications
cask java
cask macdown
cask vagrant-manager
cask vagrant
cask java7

# App Store applications
appstore 682658836 GarageBand
appstore 409183694 Keynote
appstore 409203825 Numbers
appstore 409201541 Pages
appstore 497799835 Xcode
appstore 408981434 iMovie

# Other commands
update || true
